Update java-ci.yml

diff --git a/.github/workflows/java-ci.yml b/.github/workflows/java-ci.yml
--- a/.github/workflows/java-ci.yml
+++ b/.github/workflows/java-ci.yml
@@ -17,14 +17,29 @@ jobs:
     - name: Set up JDK
       uses: actions/setup-java@v4
       with:
-        distribution: 'temurin' # See 'Supported distributions' for available options
+        distribution: 'temurin'
         java-version: '21'
+        cache: maven
 
-    - name: Build with Maven
-      run: mvn -B clean install
+    - name: Install dependencies
+      run: ./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
+      
+    - name: Run tests and collect coverage
+      run: ./mvnw -B test
 
-    - name: Run tests and generate report
-      run: mvn test
+    - name: Tree
+      run: tree -L 2
+      
+    - name: Publish Test Report
+      uses: mikepenz/action-junit-report@v4
+      if: success() || failure() # always run even if the previous step fails
+      with:
+        report_paths: 'target/surefire-reports/TEST-*.xml'
+
+    - name: Upload coverage reports to Codecov
+      uses: codecov/codecov-action@v3
+      env:
+        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
 
     - name: Push to main on success
       if: success()
